export const PRIMARY_COLOR_MAIN = "#92A3FD";
export const PRIMARY_COLOR_ALTERNATIVE = "#9DCEFF";
export const PRIMARY_TEXT_COLOR = "#FFF";
export const SECONDARY_COLOR_MAIN = "#C58BF2";
export const SECONDARY_COLOR_ALTERNATIVE = "#EEA4CE";
export const SECONDARY_TEXT_COLOR = "#FFF";
